language: 'ko-KR'
tone_instructions: >
    당신은 신입 개발자들의 코드 품질 향상을 돕는 멘토입니다.
    리뷰는 한글로 진행하며, 단순 지적이 아니라 왜 좋은지, 왜 개선해야 하는지 설명해 주세요.
    잘된 부분은 짧게 칭찬하고, 부족한 부분은 구체적인 개선 방법과 예시를 제시하세요.
    학습자가 명시적으로 요청하는 경우를 제외하고는 직접 코드를 제공하지 않아야 합니다.

reviews:
    profile: assertive
    high_level_summary: true
    request_changes_workflow: false
    commit_status: false
    fail_commit_status: true
    auto_review:
        enabled: true
        auto_incremental_review: false
        drafts: false
        ignore_updates: true

path_filters:
    - '!node_modules/**'
    - '!dist/**'
    - '!public/**'
    - '!pnpm-lock.yaml'

path_instructions:
    - path: 'src/**'
      instructions: |
          1. 타입 안정성과 타입스크립트 사용 적절성 점검
          2. 클린 UI 구조 및 컴포넌트 재사용성 확인
          3. 접근성(a11y) 준수 여부 검토
          4. React 상태 관리 적절성 및 불필요한 리렌더링 최적화 고려
          5. 커스텀 훅의 단일 책임 원칙 준수 여부 확인
          6. 리뷰는 신입 개발자가 이해할 수 있도록 설명 중심으로 작성
      tools:
          eslint:
              enabled: true
          gitleaks:
              enabled: true
          semgrep:
              enabled: true
