/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStarRouteImport } from './routes/_layout/star'
import { Route as LayoutMyRouteImport } from './routes/_layout/my'
import { Route as LayoutMapsRouteImport } from './routes/_layout/maps'
import { Route as LayoutFeedRouteImport } from './routes/_layout/feed'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutMapsIndexRouteImport } from './routes/_layout/maps/index'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth/callback.$provider'
import { Route as LayoutMapsStoreIdRouteImport } from './routes/_layout/maps/$storeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/_layout/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutStarRoute = LayoutStarRouteImport.update({
  id: '/_layout/star',
  path: '/star',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMyRoute = LayoutMyRouteImport.update({
  id: '/_layout/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMapsRoute = LayoutMapsRouteImport.update({
  id: '/_layout/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutFeedRoute = LayoutFeedRouteImport.update({
  id: '/_layout/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/_layout/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMapsIndexRoute = LayoutMapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutMapsRoute,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMapsStoreIdRoute = LayoutMapsStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => LayoutMapsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/chat': typeof LayoutChatRoute
  '/feed': typeof LayoutFeedRoute
  '/maps': typeof LayoutMapsRouteWithChildren
  '/my': typeof LayoutMyRoute
  '/star': typeof LayoutStarRoute
  '/': typeof LayoutIndexRoute
  '/maps/$storeId': typeof LayoutMapsStoreIdRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/maps/': typeof LayoutMapsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/chat': typeof LayoutChatRoute
  '/feed': typeof LayoutFeedRoute
  '/my': typeof LayoutMyRoute
  '/star': typeof LayoutStarRoute
  '/': typeof LayoutIndexRoute
  '/maps/$storeId': typeof LayoutMapsStoreIdRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/maps': typeof LayoutMapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/feed': typeof LayoutFeedRoute
  '/_layout/maps': typeof LayoutMapsRouteWithChildren
  '/_layout/my': typeof LayoutMyRoute
  '/_layout/star': typeof LayoutStarRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/maps/$storeId': typeof LayoutMapsStoreIdRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/_layout/maps/': typeof LayoutMapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/chat'
    | '/feed'
    | '/maps'
    | '/my'
    | '/star'
    | '/'
    | '/maps/$storeId'
    | '/auth/callback/$provider'
    | '/maps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/chat'
    | '/feed'
    | '/my'
    | '/star'
    | '/'
    | '/maps/$storeId'
    | '/auth/callback/$provider'
    | '/maps'
  id:
    | '__root__'
    | '/login'
    | '/_layout/chat'
    | '/_layout/feed'
    | '/_layout/maps'
    | '/_layout/my'
    | '/_layout/star'
    | '/_layout/'
    | '/_layout/maps/$storeId'
    | '/auth/callback/$provider'
    | '/_layout/maps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutFeedRoute: typeof LayoutFeedRoute
  LayoutMapsRoute: typeof LayoutMapsRouteWithChildren
  LayoutMyRoute: typeof LayoutMyRoute
  LayoutStarRoute: typeof LayoutStarRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/star': {
      id: '/_layout/star'
      path: '/star'
      fullPath: '/star'
      preLoaderRoute: typeof LayoutStarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/my': {
      id: '/_layout/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof LayoutMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/maps': {
      id: '/_layout/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof LayoutMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/feed': {
      id: '/_layout/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof LayoutFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/maps/': {
      id: '/_layout/maps/'
      path: '/'
      fullPath: '/maps/'
      preLoaderRoute: typeof LayoutMapsIndexRouteImport
      parentRoute: typeof LayoutMapsRoute
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/maps/$storeId': {
      id: '/_layout/maps/$storeId'
      path: '/$storeId'
      fullPath: '/maps/$storeId'
      preLoaderRoute: typeof LayoutMapsStoreIdRouteImport
      parentRoute: typeof LayoutMapsRoute
    }
  }
}

interface LayoutMapsRouteChildren {
  LayoutMapsStoreIdRoute: typeof LayoutMapsStoreIdRoute
  LayoutMapsIndexRoute: typeof LayoutMapsIndexRoute
}

const LayoutMapsRouteChildren: LayoutMapsRouteChildren = {
  LayoutMapsStoreIdRoute: LayoutMapsStoreIdRoute,
  LayoutMapsIndexRoute: LayoutMapsIndexRoute,
}

const LayoutMapsRouteWithChildren = LayoutMapsRoute._addFileChildren(
  LayoutMapsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutFeedRoute: LayoutFeedRoute,
  LayoutMapsRoute: LayoutMapsRouteWithChildren,
  LayoutMyRoute: LayoutMyRoute,
  LayoutStarRoute: LayoutStarRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
