/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStarRouteImport } from './routes/_layout/star'
import { Route as LayoutMyRouteImport } from './routes/_layout/my'
import { Route as LayoutFeedRouteImport } from './routes/_layout/feed'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutMapsIndexRouteImport } from './routes/_layout/maps/index'

const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/_layout/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutStarRoute = LayoutStarRouteImport.update({
  id: '/_layout/star',
  path: '/star',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMyRoute = LayoutMyRouteImport.update({
  id: '/_layout/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutFeedRoute = LayoutFeedRouteImport.update({
  id: '/_layout/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/_layout/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMapsIndexRoute = LayoutMapsIndexRouteImport.update({
  id: '/_layout/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof LayoutChatRoute
  '/feed': typeof LayoutFeedRoute
  '/my': typeof LayoutMyRoute
  '/star': typeof LayoutStarRoute
  '/': typeof LayoutIndexRoute
  '/maps/': typeof LayoutMapsIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof LayoutChatRoute
  '/feed': typeof LayoutFeedRoute
  '/my': typeof LayoutMyRoute
  '/star': typeof LayoutStarRoute
  '/': typeof LayoutIndexRoute
  '/maps': typeof LayoutMapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/feed': typeof LayoutFeedRoute
  '/_layout/my': typeof LayoutMyRoute
  '/_layout/star': typeof LayoutStarRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/maps/': typeof LayoutMapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/chat' | '/feed' | '/my' | '/star' | '/' | '/maps/'
  fileRoutesByTo: FileRoutesByTo
  to: '/chat' | '/feed' | '/my' | '/star' | '/' | '/maps'
  id:
    | '__root__'
    | '/_layout/chat'
    | '/_layout/feed'
    | '/_layout/my'
    | '/_layout/star'
    | '/_layout/'
    | '/_layout/maps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutFeedRoute: typeof LayoutFeedRoute
  LayoutMyRoute: typeof LayoutMyRoute
  LayoutStarRoute: typeof LayoutStarRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMapsIndexRoute: typeof LayoutMapsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/star': {
      id: '/_layout/star'
      path: '/star'
      fullPath: '/star'
      preLoaderRoute: typeof LayoutStarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/my': {
      id: '/_layout/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof LayoutMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/feed': {
      id: '/_layout/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof LayoutFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/maps/': {
      id: '/_layout/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof LayoutMapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LayoutChatRoute: LayoutChatRoute,
  LayoutFeedRoute: LayoutFeedRoute,
  LayoutMyRoute: LayoutMyRoute,
  LayoutStarRoute: LayoutStarRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMapsIndexRoute: LayoutMapsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
